"""Added venue table

Revision ID: 0910c8f12526
Revises: a85880f6b8e3
Create Date: 2025-09-27 01:33:50.053117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0910c8f12526'
down_revision: Union[str, Sequence[str], None] = 'a85880f6b8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acl_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_cnt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_acl_id'), 'venues', ['acl_id'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.add_column('papers', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_papers_venue'), table_name='papers')
    op.create_index(op.f('ix_papers_venue_id'), 'papers', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'papers', 'venues', ['venue_id'], ['id'])
    op.drop_column('papers', 'venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_index(op.f('ix_papers_venue_id'), table_name='papers')
    op.create_index(op.f('ix_papers_venue'), 'papers', ['venue'], unique=False)
    op.drop_column('papers', 'venue_id')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_acl_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
